export default {
  loadMore: document.querySelector("[data-load-more]"),
  btnOpenContent: document.querySelector("[data-open-content]"),
  btnCloseFilter: document.querySelector("[data-close-filter]"),
  backdrop: document.querySelector("[data-filter-backdrop]"),
  usersContainer: document.querySelector("[data-users-container]"),
  user: document.querySelector("#user-template"),
  spiner: document.querySelector("[data-load-spiner]"),
  statisticTemplate: document.querySelector("#statistics"),
  statisticContainer: document.querySelector(".statistics"),
  filter: document.querySelector(".filter"),
  form: document.querySelector("#data"),
  search: document.querySelector("[data-input-search]"),
  content: document.querySelector(".users-content"),
  select: document.querySelector("#sort-control"),
  allCheckbox: [...document.querySelectorAll('input[type="checkbox"]')],
  paginationList: document.querySelector(".pagination__list"),
  startStep: document.querySelector("#first-step"),
  endStep: document.querySelector("#last-step"),
  prevStep: document.querySelector("#prev-step"),
  nextStep: document.querySelector("#next-step"),
  selects: document.querySelectorAll("select"),
  selectPerPage: document.querySelector("#view-control"),
  dropdownFilter: document.querySelectorAll("[data-select]"),
};
